# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cdb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cdb.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tcdb.proto\"\\\n\x11TimeSeriesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x15\n\rfrom_datetime\x18\x03 \x01(\t\x12\x13\n\x0bto_datetime\x18\x04 \x01(\t\"b\n\x16MultiTimeSeriesRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\rfrom_datetime\x18\x03 \x01(\t\x12\x13\n\x0bto_datetime\x18\x04 \x01(\t\x12\x0f\n\x07metrics\x18\x06 \x03(\t\";\n\tPutResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x03\x12\x0f\n\x07message\x18\x03 \x01(\t\"*\n\tFloatItem\x12\x0e\n\x06offset\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x02\")\n\x08\x42lobItem\x12\x0e\n\x06offset\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x0c\"\"\n\x04Pair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\"\n\nDictionary\x12\x14\n\x05pairs\x18\x01 \x03(\x0b\x32\x05.Pair\"y\n\x0e\x44ictTimeSeries\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x12\n\ntimestamps\x18\x03 \x03(\x03\x12\x1b\n\x06values\x18\x04 \x03(\x0b\x32\x0b.Dictionary\x12\x19\n\x11timestamp_offsets\x18\x05 \x03(\x11\"m\n\x0f\x46loatTimeSeries\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x12\n\ntimestamps\x18\x03 \x03(\x03\x12\x0e\n\x06values\x18\x04 \x03(\x02\x12\x19\n\x11timestamp_offsets\x18\x05 \x03(\x11\"5\n\x13\x46loatTimeSeriesList\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.FloatTimeSeries2\xbf\x02\n\nTimeSeries\x12\x32\n\x08getFloat\x12\x12.TimeSeriesRequest\x1a\x10.FloatTimeSeries\"\x00\x12@\n\rgetMultiFloat\x12\x17.MultiTimeSeriesRequest\x1a\x14.FloatTimeSeriesList\"\x00\x12\x30\n\x07getDict\x12\x12.TimeSeriesRequest\x1a\x0f.DictTimeSeries\"\x00\x12*\n\x08putFloat\x12\x10.FloatTimeSeries\x1a\n.PutResult\"\x00\x12\x33\n\rputMultiFloat\x12\x14.FloatTimeSeriesList\x1a\n.PutResult\"\x00\x12(\n\x07putDict\x12\x0f.DictTimeSeries\x1a\n.PutResult\"\x00\x62\x06proto3')
)




_TIMESERIESREQUEST = _descriptor.Descriptor(
  name='TimeSeriesRequest',
  full_name='TimeSeriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='TimeSeriesRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='TimeSeriesRequest.metric', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_datetime', full_name='TimeSeriesRequest.from_datetime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_datetime', full_name='TimeSeriesRequest.to_datetime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=105,
)


_MULTITIMESERIESREQUEST = _descriptor.Descriptor(
  name='MultiTimeSeriesRequest',
  full_name='MultiTimeSeriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MultiTimeSeriesRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_datetime', full_name='MultiTimeSeriesRequest.from_datetime', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_datetime', full_name='MultiTimeSeriesRequest.to_datetime', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='MultiTimeSeriesRequest.metrics', index=3,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=205,
)


_PUTRESULT = _descriptor.Descriptor(
  name='PutResult',
  full_name='PutResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='PutResult.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='PutResult.counter', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='PutResult.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=266,
)


_FLOATITEM = _descriptor.Descriptor(
  name='FloatItem',
  full_name='FloatItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='FloatItem.offset', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='FloatItem.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=310,
)


_BLOBITEM = _descriptor.Descriptor(
  name='BlobItem',
  full_name='BlobItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='BlobItem.offset', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='BlobItem.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=353,
)


_PAIR = _descriptor.Descriptor(
  name='Pair',
  full_name='Pair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Pair.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Pair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=389,
)


_DICTIONARY = _descriptor.Descriptor(
  name='Dictionary',
  full_name='Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='Dictionary.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=425,
)


_DICTTIMESERIES = _descriptor.Descriptor(
  name='DictTimeSeries',
  full_name='DictTimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DictTimeSeries.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='DictTimeSeries.metric', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='DictTimeSeries.timestamps', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='DictTimeSeries.values', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_offsets', full_name='DictTimeSeries.timestamp_offsets', index=4,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=548,
)


_FLOATTIMESERIES = _descriptor.Descriptor(
  name='FloatTimeSeries',
  full_name='FloatTimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='FloatTimeSeries.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='FloatTimeSeries.metric', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='FloatTimeSeries.timestamps', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='FloatTimeSeries.values', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_offsets', full_name='FloatTimeSeries.timestamp_offsets', index=4,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=659,
)


_FLOATTIMESERIESLIST = _descriptor.Descriptor(
  name='FloatTimeSeriesList',
  full_name='FloatTimeSeriesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='FloatTimeSeriesList.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=714,
)

_DICTIONARY.fields_by_name['pairs'].message_type = _PAIR
_DICTTIMESERIES.fields_by_name['values'].message_type = _DICTIONARY
_FLOATTIMESERIESLIST.fields_by_name['data'].message_type = _FLOATTIMESERIES
DESCRIPTOR.message_types_by_name['TimeSeriesRequest'] = _TIMESERIESREQUEST
DESCRIPTOR.message_types_by_name['MultiTimeSeriesRequest'] = _MULTITIMESERIESREQUEST
DESCRIPTOR.message_types_by_name['PutResult'] = _PUTRESULT
DESCRIPTOR.message_types_by_name['FloatItem'] = _FLOATITEM
DESCRIPTOR.message_types_by_name['BlobItem'] = _BLOBITEM
DESCRIPTOR.message_types_by_name['Pair'] = _PAIR
DESCRIPTOR.message_types_by_name['Dictionary'] = _DICTIONARY
DESCRIPTOR.message_types_by_name['DictTimeSeries'] = _DICTTIMESERIES
DESCRIPTOR.message_types_by_name['FloatTimeSeries'] = _FLOATTIMESERIES
DESCRIPTOR.message_types_by_name['FloatTimeSeriesList'] = _FLOATTIMESERIESLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeSeriesRequest = _reflection.GeneratedProtocolMessageType('TimeSeriesRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMESERIESREQUEST,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:TimeSeriesRequest)
  ))
_sym_db.RegisterMessage(TimeSeriesRequest)

MultiTimeSeriesRequest = _reflection.GeneratedProtocolMessageType('MultiTimeSeriesRequest', (_message.Message,), dict(
  DESCRIPTOR = _MULTITIMESERIESREQUEST,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:MultiTimeSeriesRequest)
  ))
_sym_db.RegisterMessage(MultiTimeSeriesRequest)

PutResult = _reflection.GeneratedProtocolMessageType('PutResult', (_message.Message,), dict(
  DESCRIPTOR = _PUTRESULT,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:PutResult)
  ))
_sym_db.RegisterMessage(PutResult)

FloatItem = _reflection.GeneratedProtocolMessageType('FloatItem', (_message.Message,), dict(
  DESCRIPTOR = _FLOATITEM,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:FloatItem)
  ))
_sym_db.RegisterMessage(FloatItem)

BlobItem = _reflection.GeneratedProtocolMessageType('BlobItem', (_message.Message,), dict(
  DESCRIPTOR = _BLOBITEM,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:BlobItem)
  ))
_sym_db.RegisterMessage(BlobItem)

Pair = _reflection.GeneratedProtocolMessageType('Pair', (_message.Message,), dict(
  DESCRIPTOR = _PAIR,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:Pair)
  ))
_sym_db.RegisterMessage(Pair)

Dictionary = _reflection.GeneratedProtocolMessageType('Dictionary', (_message.Message,), dict(
  DESCRIPTOR = _DICTIONARY,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:Dictionary)
  ))
_sym_db.RegisterMessage(Dictionary)

DictTimeSeries = _reflection.GeneratedProtocolMessageType('DictTimeSeries', (_message.Message,), dict(
  DESCRIPTOR = _DICTTIMESERIES,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:DictTimeSeries)
  ))
_sym_db.RegisterMessage(DictTimeSeries)

FloatTimeSeries = _reflection.GeneratedProtocolMessageType('FloatTimeSeries', (_message.Message,), dict(
  DESCRIPTOR = _FLOATTIMESERIES,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:FloatTimeSeries)
  ))
_sym_db.RegisterMessage(FloatTimeSeries)

FloatTimeSeriesList = _reflection.GeneratedProtocolMessageType('FloatTimeSeriesList', (_message.Message,), dict(
  DESCRIPTOR = _FLOATTIMESERIESLIST,
  __module__ = 'cdb_pb2'
  # @@protoc_insertion_point(class_scope:FloatTimeSeriesList)
  ))
_sym_db.RegisterMessage(FloatTimeSeriesList)



_TIMESERIES = _descriptor.ServiceDescriptor(
  name='TimeSeries',
  full_name='TimeSeries',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=717,
  serialized_end=1036,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFloat',
    full_name='TimeSeries.getFloat',
    index=0,
    containing_service=None,
    input_type=_TIMESERIESREQUEST,
    output_type=_FLOATTIMESERIES,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getMultiFloat',
    full_name='TimeSeries.getMultiFloat',
    index=1,
    containing_service=None,
    input_type=_MULTITIMESERIESREQUEST,
    output_type=_FLOATTIMESERIESLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getDict',
    full_name='TimeSeries.getDict',
    index=2,
    containing_service=None,
    input_type=_TIMESERIESREQUEST,
    output_type=_DICTTIMESERIES,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putFloat',
    full_name='TimeSeries.putFloat',
    index=3,
    containing_service=None,
    input_type=_FLOATTIMESERIES,
    output_type=_PUTRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putMultiFloat',
    full_name='TimeSeries.putMultiFloat',
    index=4,
    containing_service=None,
    input_type=_FLOATTIMESERIESLIST,
    output_type=_PUTRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putDict',
    full_name='TimeSeries.putDict',
    index=5,
    containing_service=None,
    input_type=_DICTTIMESERIES,
    output_type=_PUTRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIMESERIES)

DESCRIPTOR.services_by_name['TimeSeries'] = _TIMESERIES

# @@protoc_insertion_point(module_scope)
