# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import cdb_pb2 as cdb__pb2


class TimeSeriesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getFloat = channel.unary_unary(
        '/TimeSeries/getFloat',
        request_serializer=cdb__pb2.TimeSeriesRequest.SerializeToString,
        response_deserializer=cdb__pb2.FloatTimeSeries.FromString,
        )
    self.getMultiFloat = channel.unary_unary(
        '/TimeSeries/getMultiFloat',
        request_serializer=cdb__pb2.MultiTimeSeriesRequest.SerializeToString,
        response_deserializer=cdb__pb2.FloatTimeSeriesList.FromString,
        )
    self.getDict = channel.unary_unary(
        '/TimeSeries/getDict',
        request_serializer=cdb__pb2.TimeSeriesRequest.SerializeToString,
        response_deserializer=cdb__pb2.DictTimeSeries.FromString,
        )
    self.putFloat = channel.unary_unary(
        '/TimeSeries/putFloat',
        request_serializer=cdb__pb2.FloatTimeSeries.SerializeToString,
        response_deserializer=cdb__pb2.PutResult.FromString,
        )
    self.putMultiFloat = channel.unary_unary(
        '/TimeSeries/putMultiFloat',
        request_serializer=cdb__pb2.FloatTimeSeriesList.SerializeToString,
        response_deserializer=cdb__pb2.PutResult.FromString,
        )
    self.putDict = channel.unary_unary(
        '/TimeSeries/putDict',
        request_serializer=cdb__pb2.DictTimeSeries.SerializeToString,
        response_deserializer=cdb__pb2.PutResult.FromString,
        )


class TimeSeriesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getFloat(self, request, context):
    """pull
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMultiFloat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getDict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putFloat(self, request, context):
    """push
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putMultiFloat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def putDict(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TimeSeriesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getFloat': grpc.unary_unary_rpc_method_handler(
          servicer.getFloat,
          request_deserializer=cdb__pb2.TimeSeriesRequest.FromString,
          response_serializer=cdb__pb2.FloatTimeSeries.SerializeToString,
      ),
      'getMultiFloat': grpc.unary_unary_rpc_method_handler(
          servicer.getMultiFloat,
          request_deserializer=cdb__pb2.MultiTimeSeriesRequest.FromString,
          response_serializer=cdb__pb2.FloatTimeSeriesList.SerializeToString,
      ),
      'getDict': grpc.unary_unary_rpc_method_handler(
          servicer.getDict,
          request_deserializer=cdb__pb2.TimeSeriesRequest.FromString,
          response_serializer=cdb__pb2.DictTimeSeries.SerializeToString,
      ),
      'putFloat': grpc.unary_unary_rpc_method_handler(
          servicer.putFloat,
          request_deserializer=cdb__pb2.FloatTimeSeries.FromString,
          response_serializer=cdb__pb2.PutResult.SerializeToString,
      ),
      'putMultiFloat': grpc.unary_unary_rpc_method_handler(
          servicer.putMultiFloat,
          request_deserializer=cdb__pb2.FloatTimeSeriesList.FromString,
          response_serializer=cdb__pb2.PutResult.SerializeToString,
      ),
      'putDict': grpc.unary_unary_rpc_method_handler(
          servicer.putDict,
          request_deserializer=cdb__pb2.DictTimeSeries.FromString,
          response_serializer=cdb__pb2.PutResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TimeSeries', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
