# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/protos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/protos.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12proto/protos.proto\"*\n\tFloatItem\x12\x0e\n\x06offset\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x02\")\n\x08\x42lobItem\x12\x0e\n\x06offset\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x0c\"s\n\x0f\x46loatTimeSeries\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\x12\n\ntimestamps\x18\x03 \x03(\x03\x12\x0e\n\x06values\x18\x04 \x03(\x02\x12\x19\n\x11timestamp_offsets\x18\x05 \x03(\x11\"5\n\x13\x46loatTimeSeriesList\x12\x1e\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x10.FloatTimeSeriesb\x06proto3')
)




_FLOATITEM = _descriptor.Descriptor(
  name='FloatItem',
  full_name='FloatItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='FloatItem.offset', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='FloatItem.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=64,
)


_BLOBITEM = _descriptor.Descriptor(
  name='BlobItem',
  full_name='BlobItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='BlobItem.offset', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='BlobItem.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=107,
)


_FLOATTIMESERIES = _descriptor.Descriptor(
  name='FloatTimeSeries',
  full_name='FloatTimeSeries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='FloatTimeSeries.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metric', full_name='FloatTimeSeries.metric', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='FloatTimeSeries.timestamps', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='FloatTimeSeries.values', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_offsets', full_name='FloatTimeSeries.timestamp_offsets', index=4,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=224,
)


_FLOATTIMESERIESLIST = _descriptor.Descriptor(
  name='FloatTimeSeriesList',
  full_name='FloatTimeSeriesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='FloatTimeSeriesList.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=279,
)

_FLOATTIMESERIESLIST.fields_by_name['data'].message_type = _FLOATTIMESERIES
DESCRIPTOR.message_types_by_name['FloatItem'] = _FLOATITEM
DESCRIPTOR.message_types_by_name['BlobItem'] = _BLOBITEM
DESCRIPTOR.message_types_by_name['FloatTimeSeries'] = _FLOATTIMESERIES
DESCRIPTOR.message_types_by_name['FloatTimeSeriesList'] = _FLOATTIMESERIESLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatItem = _reflection.GeneratedProtocolMessageType('FloatItem', (_message.Message,), dict(
  DESCRIPTOR = _FLOATITEM,
  __module__ = 'proto.protos_pb2'
  # @@protoc_insertion_point(class_scope:FloatItem)
  ))
_sym_db.RegisterMessage(FloatItem)

BlobItem = _reflection.GeneratedProtocolMessageType('BlobItem', (_message.Message,), dict(
  DESCRIPTOR = _BLOBITEM,
  __module__ = 'proto.protos_pb2'
  # @@protoc_insertion_point(class_scope:BlobItem)
  ))
_sym_db.RegisterMessage(BlobItem)

FloatTimeSeries = _reflection.GeneratedProtocolMessageType('FloatTimeSeries', (_message.Message,), dict(
  DESCRIPTOR = _FLOATTIMESERIES,
  __module__ = 'proto.protos_pb2'
  # @@protoc_insertion_point(class_scope:FloatTimeSeries)
  ))
_sym_db.RegisterMessage(FloatTimeSeries)

FloatTimeSeriesList = _reflection.GeneratedProtocolMessageType('FloatTimeSeriesList', (_message.Message,), dict(
  DESCRIPTOR = _FLOATTIMESERIESLIST,
  __module__ = 'proto.protos_pb2'
  # @@protoc_insertion_point(class_scope:FloatTimeSeriesList)
  ))
_sym_db.RegisterMessage(FloatTimeSeriesList)


# @@protoc_insertion_point(module_scope)
